import XCTest

// Ported from the ClipBoxCore scratch package (d2f81a0) against the merged
// ClipClassifier/ClipPreview/ClipHistory/ClipItem in Shared.

final class ClipExclusionTests: XCTestCase {
    // A password copied out of a manager must never reach clipbox.json: the
    // snapshot is world-readable JSON and the widget draws it on the desktop.
    func testConcealedPasteboardIsExcluded() {
        XCTAssertTrue(ClipClassifier.isExcluded(types: ["org.nspasteboard.ConcealedType"]))
        XCTAssertTrue(ClipClassifier.isExcluded(types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]))
    }

    func testTransientAndAutoGeneratedAreExcluded() {
        XCTAssertTrue(ClipClassifier.isExcluded(types: ["org.nspasteboard.TransientType"]))
        XCTAssertTrue(ClipClassifier.isExcluded(types: ["org.nspasteboard.AutoGeneratedType"]))
    }

    func testOnePasswordLegacyMarkerIsExcluded() {
        XCTAssertTrue(ClipClassifier.isExcluded(types: ["public.string", "com.agilebits.onepassword"]))
    }

    func testOrdinaryCopiesAreNotExcluded() {
        XCTAssertFalse(ClipClassifier.isExcluded(types: ["public.string"]))
        XCTAssertFalse(ClipClassifier.isExcluded(types: ["public.file-url", "public.url"]))
        XCTAssertFalse(ClipClassifier.isExcluded(types: ["public.tiff", "public.png"]))
        XCTAssertFalse(ClipClassifier.isExcluded(types: []))
    }

    // Exclusion is checked before classification, so a concealed *file* or
    // image drop is dropped too — not just concealed text.
    func testExclusionBeatsEveryKind() {
        for kindType in ["public.file-url", "public.string", "public.png", "com.unknown.thing"] {
            XCTAssertTrue(
                ClipClassifier.isExcluded(types: [kindType, "org.nspasteboard.ConcealedType"]),
                "\(kindType) with a concealed marker must still be excluded"
            )
        }
    }
}

final class ClipClassifierTests: XCTestCase {
    func testTextTypesClassifyAsText() {
        XCTAssertEqual(ClipClassifier.kind(for: ["public.string"]), .text)
        XCTAssertEqual(ClipClassifier.kind(for: ["public.utf8-plain-text"]), .text)
        XCTAssertEqual(ClipClassifier.kind(for: ["public.rtf", "com.apple.traditional-mac-plain-text"]), .text)
        XCTAssertEqual(ClipClassifier.kind(for: ["public.html"]), .text)
    }

    func testFileURLClassifiesAsFileEvenWithText() {
        XCTAssertEqual(ClipClassifier.kind(for: ["public.file-url"]), .file)
        XCTAssertEqual(ClipClassifier.kind(for: ["public.file-url", "public.url"]), .file)
        XCTAssertEqual(ClipClassifier.kind(for: ["public.file-url", "public.string"]), .file)
    }

    func testImageTypesClassifyAsImage() {
        XCTAssertEqual(ClipClassifier.kind(for: ["public.tiff"]), .image)
        XCTAssertEqual(ClipClassifier.kind(for: ["public.png"]), .image)
        XCTAssertEqual(ClipClassifier.kind(for: ["public.jpeg", "public.tiff"]), .image)
    }

    func testUnknownTypesClassifyAsOther() {
        XCTAssertEqual(ClipClassifier.kind(for: []), .other)
        XCTAssertEqual(ClipClassifier.kind(for: ["com.someapp.custom-type"]), .other)
    }
}

final class ClipPreviewTests: XCTestCase {
    func testTextPreviewTakesFirstLineAndTruncates() {
        let item = ClipItem.make(kind: .text, content: "hello world", detail: nil, date: .now)
        XCTAssertEqual(item.preview, "hello world")
        XCTAssertEqual(item.detail, "")

        let long = ClipItem.make(kind: .text, content: String(repeating: "x", count: 200), detail: nil, date: .now)
        XCTAssertEqual(long.preview.count, 80)
        XCTAssertTrue(long.preview.hasSuffix("…"))
    }

    func testTextPreviewSkipsToSecondLineWhenFirstIsEmpty() {
        let item = ClipItem.make(kind: .text, content: "\nsecond line content", detail: nil, date: .now)
        XCTAssertEqual(item.preview, "second line content")
    }

    func testTextContentIsCappedAtFourKilobytes() {
        let item = ClipItem.make(kind: .text, content: String(repeating: "y", count: 10000), detail: nil, date: .now)
        XCTAssertEqual(item.content?.count, 4096)
    }

    func testImagePreviewShowsSize() {
        let item = ClipItem.make(kind: .image, content: nil, detail: "1.2 MB", date: .now)
        XCTAssertEqual(item.preview, "Image")
        XCTAssertEqual(item.detail, "1.2 MB")
    }

    func testFilePreviewUsesLastPathComponent() {
        let item = ClipItem.make(kind: .file, content: "file:///Users/aliz/dev/at/deck/README.md", detail: nil, date: .now)
        XCTAssertEqual(item.preview, "README.md")
        XCTAssertEqual(item.detail, "file:///Users/aliz/dev/at/deck/README.md")
    }

    func testOtherKind() {
        let item = ClipItem.make(kind: .other, content: nil, detail: nil, date: .now)
        XCTAssertEqual(item.preview, "Other")
        XCTAssertEqual(item.detail, "")
    }

    func testSizeStringFormatting() {
        XCTAssertEqual(ClipPreview.sizeString(512), "512 B")
        XCTAssertEqual(ClipPreview.sizeString(1536), "1.5 KB")
        XCTAssertEqual(ClipPreview.sizeString(1_210_000), "1.2 MB")
    }
}

final class ClipHistoryTests: XCTestCase {
    private func textItem(_ content: String, date: Date = .now) -> ClipItem {
        ClipItem.make(kind: .text, content: content, detail: nil, date: date)
    }

    func testMergePrependsNewItems() {
        let a = textItem("a")
        let merged = ClipHistory.merge(existing: [a], new: textItem("b", date: a.date.addingTimeInterval(60)), maxCount: 5)
        XCTAssertEqual(merged.map(\.preview), ["b", "a"])
    }

    func testIdenticalTopCopyRefreshesWithoutDuplicating() {
        let first = textItem("same")
        let second = textItem("same", date: first.date.addingTimeInterval(60))
        let merged = ClipHistory.merge(existing: [first], new: second, maxCount: 5)
        XCTAssertEqual(merged.count, 1)
        XCTAssertEqual(merged.first?.date, second.date)
    }

    func testRepeatCopyMovesToTopWithoutDuplicating() {
        // existing is newest-first: c (newest), b, a (oldest)
        let a = textItem("a")
        let b = textItem("b", date: a.date.addingTimeInterval(60))
        let c = textItem("c", date: b.date.addingTimeInterval(60))
        let merged = ClipHistory.merge(
            existing: [c, b, a],
            new: textItem("b", date: c.date.addingTimeInterval(60)),
            maxCount: 5
        )
        XCTAssertEqual(merged.map(\.preview), ["b", "c", "a"])
    }

    func testMergeTrimsToMaxCount() {
        // existing is newest-first: item9 (newest) … item0 (oldest)
        let existing = (0..<10).reversed().map { i in
            textItem("item\(i)", date: .now.addingTimeInterval(TimeInterval(i)))
        }
        let merged = ClipHistory.merge(existing: existing, new: textItem("new"), maxCount: 5)
        XCTAssertEqual(merged.count, 5)
        XCTAssertEqual(merged.first?.preview, "new")
        XCTAssertEqual(merged.last?.preview, "item6")
    }

    func testMaxCountZeroProducesEmptyHistory() {
        let existing = [textItem("a")]
        let merged = ClipHistory.merge(existing: existing, new: textItem("b"), maxCount: 0)
        XCTAssertTrue(merged.isEmpty)
    }

    func testFileItemsDedupeOnURL() {
        let url = "file:///Users/aliz/dev/at/deck/README.md"
        let first = ClipItem.make(kind: .file, content: url, detail: nil, date: .now)
        let second = ClipItem.make(kind: .file, content: url, detail: nil, date: .now.addingTimeInterval(30))
        let merged = ClipHistory.merge(existing: [first], new: second, maxCount: 5)
        XCTAssertEqual(merged.count, 1)
    }

    func testImageCopiesAreNotDedupedWithoutDetail() {
        let first = ClipItem.make(kind: .image, content: nil, detail: nil, date: .now)
        let second = ClipItem.make(kind: .image, content: nil, detail: nil, date: .now.addingTimeInterval(30))
        let merged = ClipHistory.merge(existing: [first], new: second, maxCount: 5)
        XCTAssertEqual(merged.count, 2)
    }
}
